import os
import json
import glob
from typing import List, Dict
from pydantic import BaseModel, Field

from langchain_core.tools import tool
from langchain_core.messages import SystemMessage, AIMessage, HumanMessage

# Importing the models as per your setup
from models.gemini_models import GEMINI_31_PRO
from models.openai_models import GPT_4O_MINI, GPT_5_MINI_TEST, GPT_52_CHAT, GPT_51_CODEX_MINI, GPT_53_CODEX


# ==========================================
# 1. Pydantic Models for Structured Output
# ==========================================

class FileSelection(BaseModel):
    target_files: List[str] = Field(
        description="List of relative file paths that need editing to fix the issue"
    )


class FileUpdate(BaseModel):
    file_path: str = Field(
        description="The  path of the file to be updated"
    )
    content: str = Field(
        description="The complete new, fixed content for the file"
    )


class CodebaseMap(BaseModel):
    files: List[FileUpdate] = Field(
        description="List of complete file path related to project root to update with their new content"
    )


SELECTION_LLM = GPT_4O_MINI.with_structured_output(FileSelection)
FIX_LLM = GPT_53_CODEX.with_structured_output(CodebaseMap)


# ==========================================
# 2. LangChain Tool Definition
# ==========================================


def code_editing_agent(edit_prompt: str, project_folder_path: str) -> str:
    """
    Analyzes project metadata to decide which files need fixing, extracts their content,
    sends them to GEMINI_31_PRO to generate the corrected code, and updates the files on disk.

    Send the absolute path of the project folder and the issue to be fixed.
    The agent will handle the rest, including locating the latest metadata snapshot,
    determining which files to edit, and applying the fixes.
    """

    print("\n==================================================")
    print("🚀 STARTING CODE FIXING AGENT")
    print("==================================================")
    print(f"Issue: {edit_prompt}")
    print(f"Target Directory: {project_folder_path}")
    print("==================================================\n")

    # --- STEP 1: Locate and Read Metadata ---
    print("[Step 1] Locating and reading project metadata...")

    latest_dir = project_folder_path
    metadata_path = os.path.join(latest_dir, "project_metadata.json")

    if not os.path.exists(metadata_path):
        error_msg = f"Error: project_metadata.json not found at {metadata_path}"
        print(f"✖ {error_msg}")
        return error_msg

    with open(metadata_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    metadata_str = json.dumps(metadata, indent=2)
    print(f"Metadata snapshot loaded from: {metadata_str[:200]}...")  # Print the beginning of the metadata for verification

    print("✔ Metadata loaded successfully.")

    # --- STEP 2: Decide Which Files to Edit ---
    print("[Step 2] Analyzing metadata to select target files...")

    max_paths = 10

    selection_sys_prompt = (
        "You are a codebase router whose sole task is to choose the most relevant set "
        "of existing files to edit based on a user's request. The request will typically be "
        "either adding a new feature or debugging/fixing an existing issue.\n\n"
        "OUTPUT FORMAT:\n"
        "- Return ONLY valid JSON: {\"paths\": [\"file1_path\", \"file2_path\"]}\n"
        f"- Maximum entries: {max_paths}\n"
        "- Do NOT add explanations, markdown blocks, or extra text.\n\n"
        "SELECTION RULES:\n"
        "1) FOR FEATURE ADDITIONS: Select core files where new UI components, business logic, state management, or routing must be integrated.\n"
        "2) FOR BUG FIXES: Select files most likely to contain the faulty logic, focusing on modules related to the described unexpected behavior or stack trace.\n"
        "3) Prefer dependency proximity (e.g., select a component and its direct data-fetching service if both require changes).\n"
        "4) Give the complete paths of the files relative to the project root, ensuring they are valid and exist in the metadata snapshot.\n"
        "5) Avoid unrelated, compiled, or autogenerated files.\n"

    )

    user_block = (
        "--- EDIT REQUEST ---\n"
        "Analyze the following request to determine if it is a feature addition or a bug fix:\n"
        f"{edit_prompt}\n\n"
        "--- Project Metadata: ---\n"
        + "```json\n"
        + metadata_str
        + "\n```"
        "Remember: Return ONLY valid JSON with the selected file paths."
    )

    selection_messages = [
        SystemMessage(content=selection_sys_prompt),
        HumanMessage(content=user_block)
    ]

    print("Waiting for Architect Agent (SELECTION_LLM) to choose files...")

    selection_response: FileSelection = SELECTION_LLM.invoke(
        selection_messages
    )

    target_files = selection_response.target_files
    print(f"SELECTION_LLM response: {target_files}")

    if not target_files:
        abort_msg = (
            "Task aborted: The agent determined that no files require "
            "modification to resolve this issue."
        )
        print(f"✖ {abort_msg}")
        return abort_msg

    print("✔ Architect Agent selected the following files:")
    print(f"↳ {', '.join(target_files)}")

    # --- STEP 3: Gather Content of Target Files ---
    print("[Step 3] Gathering content of target files...")

    files_context = {}

    for rel_path in target_files:
        abs_path = os.path.join(project_folder_path, rel_path)

        if os.path.exists(abs_path):
            with open(abs_path, "r", encoding="utf-8") as f:
                files_context[rel_path] = f.read()
        else:
            files_context[rel_path] = (
                f"// New file to be created or file missing on disk: {rel_path}"
            )
            print(f"⚠ File not found on disk, marked for creation: {rel_path}")

    context_json = json.dumps(files_context, indent=2)

    print("✔ File contents gathered.")

    # --- STEP 4: Send to Gemini 3.1 Pro for the Code Fix ---
    print("[Step 4] Generating fixed code using GEMINI_31_PRO...")

    system_prompt = (
        "You are an expert code refactoring assistant.\n"
        "You will receive a JSON structure containing multiple code files and a rewriting instruction.\n"
        "Your task:\n"
        "1. Analyze each file's code.\n"
        "2. Apply the requested changes according to the prompt.\n"
        "3. Return the rewritten code for each provided file.\n"
        "4. Identify and generate any new files that are necessary to fully implement the changes or improve the architecture, even if they are not present in the current project.\n"
        "5. Ensure that the rewritten code is functional, maintainable, and adheres to best practices.\n"
        "6. Asset Generation: If you need to create new image files, generate only SVG files. For all other images or media types, use external URLs instead of creating local files.\n"
        "Maintain code quality, follow best practices, and preserve functionality unless instructed otherwise."
    )

    history = []

    user_prompt = (
        "Here is the current codebase structure and content in JSON format:\n\n"
        f"{metadata_str}\n\n"
        "Here are the files to rewrite:\n\n"
        f"{context_json}\n\n"
        "Issue in the code:\n"
        f"{edit_prompt}\n\n"
        "Please rewrite the code for each file according to the instructions above.\n"
    )

    messages = [
        SystemMessage(content=system_prompt),
        AIMessage(content=f"LLM Output History:\n{chr(10).join(history)}"),
        HumanMessage(content=user_prompt),
    ]

    print("Waiting for Developer Agent (FIX_LLM) to write code...")

    response: CodebaseMap = FIX_LLM.invoke(messages)

        # ... [Previous setup and LLM invocation code remains the same] ...

    print(f"✔ Code successfully generated for {len(response.files)} files.")

    # --- STEP 5: Update and Create Files on Disk ---
    print("[Step 5] Writing files to disk...")

    updated_list = []
    created_list = []

    for file_update in response.files:
        abs_path = os.path.join(
            project_folder_path,
            file_update.file_path
        )

        # Determine if this is a new file before creating directories/writing
        is_new_file = not os.path.exists(abs_path)

        # Ensure target directory structures exist
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)

        # Write the content to disk (creates new or overwrites existing)
        with open(abs_path, "w", encoding="utf-8") as f:
            f.write(file_update.content)

        # Track and log based on file status
        if is_new_file:
            created_list.append(file_update.file_path)
            print(f"↳ Created new file: {file_update.file_path}")
        else:
            updated_list.append(file_update.file_path)
            print(f"↳ Wrote changes to: {file_update.file_path}")

    print(f"✔ All files processed on disk ({len(updated_list)} updated, {len(created_list)} created).")

    # --- STEP 6: Return Message to the Agent ---
    # Dynamically build the success message for accurate agent context
    success_msg_parts = ["Success. The codebase has been processed."]
    
    if updated_list:
        success_msg_parts.append(f"Updated files: {', '.join(updated_list)}.")
    if created_list:
        success_msg_parts.append(f"Newly created files: {', '.join(created_list)}.")

    success_msg = " ".join(success_msg_parts)
    
    # You can now pass success_msg back into your agent's memory or observation loop

    print("\n==================================================")
    print("🎉 AGENT TASK COMPLETE")
    print("==================================================")
    print(success_msg)
    print("==================================================\n")

    return success_msg



if __name__ == "__main__":

    project_path = "D:/Development/new_vibe_code/generated/latest_2026-05-07_10-43-55"

    prompt = """
    Make the UI more modern and visually appealing.  Use a clean, minimalist design with a light color scheme. Ensure the layout is responsive for both desktop and mobile devices.
    """

    result = code_editing_agent(
        edit_prompt=prompt,
        project_folder_path=project_path
    )

    print("\nFINAL RESULT:")
    print(result)