import os
import json
import glob
from typing import List, Dict
from pydantic import BaseModel, Field

from langchain_core.tools import tool
from langchain_core.messages import SystemMessage, AIMessage, HumanMessage

# Importing the models as per your setup
from models.gemini_models import GEMINI_31_PRO
from models.openai_models import GPT_4O_MINI, GPT_5_MINI_TEST, GPT_52_CHAT, GPT_51_CODEX_MINI, GPT_53_CODEX

# --- NEW: Import Rich for rich text logging ---
from rich.console import Console
from rich.panel import Panel

# Initialize the Rich Console
console = Console()

# ==========================================
# 1. Pydantic Models for Structured Output
# ==========================================

class FileSelection(BaseModel):
    target_files: List[str] = Field(description="List of relative file paths that need editing to fix the issue")

class FileUpdate(BaseModel):
    file_path: str = Field(description="The relative path of the file to be updated")
    content: str = Field(description="The complete new, fixed content for the file")

class CodebaseMap(BaseModel):
    files: List[FileUpdate] = Field(description="List of files to update with their new content")


SELECTION_LLM = GPT_53_CODEX.with_structured_output(FileSelection)
FIX_LLM = GEMINI_31_PRO.with_structured_output(CodebaseMap)

# ==========================================
# 2. LangChain Tool Definition
# ==========================================

@tool
def code_fixing_agent(issue: str, project_folder_path: str) -> str:
    """
    Analyzes project metadata to decide which files need fixing, extracts their content, 
    sends them to GEMINI_31_PRO to generate the corrected code, and updates the files on disk.
    send the absolute path of the project folder and the issue to be fixed. The agent will handle the rest, including locating the latest metadata snapshot, determining which files to edit, and applying the fixes.
    """
    
    # Display an introductory panel for the task
    console.print(Panel(f"[bold cyan]Issue:[/bold cyan] {issue}\n[bold cyan]Target Directory:[/bold cyan] {project_folder_path}", 
                        title="[bold blue]🚀 Starting Code Fixing Agent[/bold blue]", expand=False))

    # --- STEP 1: Locate and Read Metadata ---
    console.print("[bold yellow][Step 1][/bold yellow] Locating and reading project metadata...")
    
    latest_dir = project_folder_path
    metadata_path = os.path.join(latest_dir, "project_metadata.json")
    
    if not os.path.exists(metadata_path):
        error_msg = f"Error: project_metadata.json not found at {metadata_path}"
        console.log(f"[bold red]✖ {error_msg}[/bold red]")
        return error_msg
        
    with open(metadata_path, 'r', encoding='utf-8') as f:
        metadata = json.load(f)
        
    metadata_str = json.dumps(metadata, indent=2)
    console.print("[bold green]✔ Metadata loaded successfully.[/bold green]")

    # --- STEP 2: Decide Which Files to Edit ---
    console.print("[bold yellow][Step 2][/bold yellow] Analyzing metadata to select target files...")
    
    max_paths = 10  # Limit the number of files to select for editing
    selection_sys_prompt =(
        "You are a codebase debugging and repair router whose sole task is to choose the most relevant set "
        "of existing files to inspect and modify based on a user's issue or failure report. The request will "
        "typically involve runtime errors, QA failures, broken functionality, UI issues, or application crashes.\n\n"
        "OUTPUT FORMAT:\n"
        "- Return ONLY valid JSON: {\"paths\": [\"file1\", \"file2\"]}\n"
        f"- Maximum entries: {max_paths}\n"
        "- Do NOT add explanations, markdown blocks, or extra text.\n\n"
        "SELECTION RULES:\n"
        "1) FOR RUNTIME/LOG ERRORS: Select files directly related to the stack trace, failing module, dependency injection path, imports, providers, services, or affected component.\n"
        "2) FOR UI/QA FAILURES: Select files responsible for rendering, styling, routing, state handling, data flow, or event interactions connected to the reported behavior.\n"
        "3) Prefer dependency proximity (e.g., select a component and its direct service, config, provider, or API integration if both may require changes).\n"
        "5) Avoid unrelated, compiled, generated, vendor, cache, dist, or autogenerated files.\n"
    )


    selection_messages = [
        SystemMessage(content=selection_sys_prompt),
        HumanMessage(content=f"Issue to fix:\n{issue}\n\nProject Metadata:\n{metadata_str}")
    ]
    
    # Use a Rich status spinner while waiting for the LLM
    with console.status("[bold cyan]Waiting for Architect Agent (SELECTION_LLM) to choose files...[/bold cyan]", spinner="dots"):
        selection_response: FileSelection = SELECTION_LLM.invoke(selection_messages)
        target_files = selection_response.target_files
    
    if not target_files:
        abort_msg = "Task aborted: The agent determined that no files require modification to resolve this issue."
        console.print(f"[bold red]✖ {abort_msg}[/bold red]")
        return abort_msg
        
    console.print(f"[bold green]✔ Architect Agent selected the following files:[/bold green]\n  [dim]↳ {', '.join(target_files)}[/dim]")

    # --- STEP 3: Gather Content of Target Files ---
    console.print("[bold yellow][Step 3][/bold yellow] Gathering content of target files...")
    files_context = {}
    
    for rel_path in target_files:
        abs_path = os.path.join(project_folder_path, rel_path)
        if os.path.exists(abs_path):
            with open(abs_path, 'r', encoding='utf-8') as f:
                files_context[rel_path] = f.read()
        else:
            files_context[rel_path] = f"// New file to be created or file missing on disk: {rel_path}"
            console.print(f"  [dim]⚠ File not found on disk, marked for creation: {rel_path}[/dim]")

    context_json = json.dumps(files_context, indent=2)
    console.print("[bold green]✔ File contents gathered.[/bold green]")

    # --- STEP 4: Send to Gemini 3.1 Pro for the Code Fix ---
    console.print("[bold yellow][Step 4][/bold yellow] Generating fixed code using GEMINI_31_PRO...")
    
    system_prompt =  (
            "You are an expert code refactoring assistant.\n"
            "You will receive a JSON structure containing multiple code files and a rewriting instruction.\n"
            "Your task:\n"
            "1. Analyze each file's code.\n"
            "2. Apply the requested changes according to the prompt.\n"
            "3. Return the rewritten code for each provided file.\n"
            "4. Identify and generate any new files that are necessary to fully implement the changes or improve the architecture, even if they are not present in the current project.\n"
            "5. Ensure that the rewritten code is functional, maintainable, and adheres to best practices.\n"
            "6. Asset Generation: If you need to create new image files, generate only SVG files. For all other images or media types, use external URLs instead of creating local files.\n"
            "Maintain code quality, follow best practices, and preserve functionality unless instructed otherwise."
        )
    
    history = []
    user_prompt = f"Issue:\n{issue}\n\nTarget Files Content:\n{context_json}"

    user_prompt =  (
            "Here is the current codebase structure and content in JSON format:\n\n"
            f"{metadata_str}\n\n"
            "Here are the files to rewrite:\n\n"
            f"{context_json}\n\n"
            "Issue in the code:\n"
            f"{issue}\n\n"
            "Please rewrite the code for each file according to the instructions above.\n"
        )

    
    messages = [
        SystemMessage(content=system_prompt),
        AIMessage(content=f"LLM Output History:\n{chr(10).join(history)}"),
        HumanMessage(content=user_prompt),
    ]
            
    # Use another Rich status spinner while waiting for Gemini to write the code
    with console.status("[bold magenta]Waiting for Developer Agent (FIX_LLM) to write code...[/bold magenta]", spinner="bouncingBar"):
        response: CodebaseMap = FIX_LLM.invoke(messages)
        
    console.print(f"[bold green]✔ Code successfully generated for {len(response.files)} files.[/bold green]")

    # --- STEP 5: Update the Files on Disk ---
    console.print("[bold yellow][Step 5][/bold yellow] Writing updated files to disk...")
    updated_list = []
    
    for file_update in response.files:
        abs_path = os.path.join(project_folder_path, file_update.file_path)
        
        # Ensure target directory structures exist (e.g., if creating a new nested file)
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)
        
        with open(abs_path, 'w', encoding='utf-8') as f:
            f.write(file_update.content)
            
        updated_list.append(file_update.file_path)
        console.print(f"  [dim]↳ Wrote changes to: {file_update.file_path}[/dim]")

    console.print("[bold green]✔ All files updated on disk.[/bold green]")

    # --- STEP 6: Return Message to the Agent ---
    success_msg = f"Success. The codebase has been fixed. The following files were updated: {', '.join(updated_list)}"
    
    # Final success panel
    console.print(Panel(success_msg, title="[bold green]🎉 Agent Task Complete[/bold green]", expand=False))
    
    return success_msg